### ISSUE TITLE
 Users can track NA teams

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/Ajax-project-NALCS#1]

**Comment by leejaejoseph** [comment]
## 🖼️ Wireframes

![user can track NA teams mobile](https://user-images.githubusercontent.com/116613246/211396203-377706c4-5c61-47a3-9492-912be9f14ef8.png)
![user can track NA teams desktop](https://user-images.githubusercontent.com/116613246/211396102-022d45f0-5766-4473-9622-7a39d6203c7d.png)

## ✅ Task List
- [ ] Create HTML Layout for top navbar.
  - [ ] Make the Teams Button in Navbar link to the Teams page.
- [ ] Setup layout of page with three rows for the H1, 10 team clickers, and selected teams button.
  - [ ] Write CSS for mobile devices first.
  - [ ] Adjust styling to fluidly adapt to desktop.
- [ ] For each button, Add a 'click' event listener that:
  - [ ] changes the background-color of the selected icon:
    - [ ] turns on when it was off.
    - [ ] turns off when it was on. 
  - [ ] stores the selected teams into the data model object if button is turned on
  - [ ] removes selected teams in the data model object if button is turned off
- [ ] Add a `'submit'` event listener for the Teams page that:
  - [ ] prevents the page from refreshing when the form is submitted.
  - [ ] copies the selected teams in the data model object into the stored teams data model object.
- [ ] In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [ ] At the bottom of `data.js`, include a conditional statement that:
  - [ ] checks to see if there is a JSON data model stored in `localStorage`.
  - [ ] if there is, parse it and assign it to the initial `data` variable so that the user can view their previous instance after load from the pre-existing data model.
- [ ] Test the app by selecting and submitting teams and then reloading the page to confirm that:
  - [ ] the data model is being saved to `localStorage` before each page reload.
  - [ ] the data model stores the selected teams and is stored if the submit button was clicked
- [ ] Remove all CSS styling that ht had no affect or was otherwise unnecessary.ad no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
